included:
  - Source
  - CocoaMQTTTests

excluded:
  - .build
  - Carthage
  - Pods
  - Example
  - CocoaMQTT.xcodeproj

disabled_rules:
  - computed_accessors_order
  - cyclomatic_complexity
  - empty_enum_arguments
  - file_length
  - force_cast
  - force_try
  - for_where
  - function_body_length
  - function_parameter_count
  - identifier_name
  - implicit_getter
  - implicit_optional_initialization
  - legacy_random
  - line_length
  - orphaned_doc_comment
  - return_arrow_whitespace
  - shorthand_operator
  - static_over_final_class
  - todo
  - type_body_length
  - type_name
  - unneeded_override
  - unneeded_synthesized_initializer
  - unused_optional_binding
  - void_return

reporter: "xcode"
