excluded:
  - Pods
  - .build

line_length: 160
disabled_rules:
  - cyclomatic_complexity
  - file_length
  - force_cast
  - function_body_length
  - todo
  - type_body_length

identifier_name:
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 1
