included:
  - Source
  - CocoaMQTTTests

excluded:
  - .build
  - Carthage
  - Pods
  - Example
  - CocoaMQTT.xcodeproj

disabled_rules:
  - cyclomatic_complexity
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - identifier_name
  - line_length
  - todo
  - type_body_length
  - type_name

reporter: "xcode"
